// GENERATED by scripts/gen-icon-pack.mjs — do not edit by hand. To add an
// icon, import it from '@/lib/icon-pack' and run `npm run icons:gen`.
//
// Pack-aware icons: every icon the app uses, exported under its Lucide name.
// Each renders the Lucide, Hugeicons, Phosphor or Tabler equivalent depending
// on the active pack (useIconPack — cookie-backed, SSR-safe).
import { defineComponent, h, type Component } from 'vue'
import { HugeiconsIcon } from '@hugeicons/vue'
import {
  Activity as LActivity,
  AlertCircle as LAlertCircle,
  AlertTriangle as LAlertTriangle,
  AlignCenter as LAlignCenter,
  AlignLeft as LAlignLeft,
  AlignRight as LAlignRight,
  Archive as LArchive,
  ArrowDown as LArrowDown,
  ArrowDownRight as LArrowDownRight,
  ArrowLeft as LArrowLeft,
  ArrowRight as LArrowRight,
  ArrowUp as LArrowUp,
  ArrowUpDown as LArrowUpDown,
  ArrowUpRight as LArrowUpRight,
  AudioWaveform as LAudioWaveform,
  BadgeCheck as LBadgeCheck,
  BarChart3 as LBarChart3,
  Bell as LBell,
  BellOff as LBellOff,
  Bold as LBold,
  BookOpen as LBookOpen,
  Boxes as LBoxes,
  Briefcase as LBriefcase,
  Bug as LBug,
  Building2 as LBuilding2,
  Calendar as LCalendar,
  CalendarDays as LCalendarDays,
  CalendarIcon as LCalendarIcon,
  CalendarPlus as LCalendarPlus,
  Check as LCheck,
  CheckCheck as LCheckCheck,
  CheckCircle2 as LCheckCircle2,
  ChevronDown as LChevronDown,
  ChevronDownIcon as LChevronDownIcon,
  ChevronLeft as LChevronLeft,
  ChevronRight as LChevronRight,
  ChevronUp as LChevronUp,
  ChevronsLeft as LChevronsLeft,
  ChevronsRight as LChevronsRight,
  ChevronsUpDown as LChevronsUpDown,
  Chrome as LChrome,
  Circle as LCircle,
  CircleAlert as LCircleAlert,
  CircleCheckIcon as LCircleCheckIcon,
  CircleDot as LCircleDot,
  Clock as LClock,
  CloudOff as LCloudOff,
  Code as LCode,
  Columns3 as LColumns3,
  Command as LCommand,
  Copy as LCopy,
  CopyPlus as LCopyPlus,
  CreditCard as LCreditCard,
  DollarSign as LDollarSign,
  Download as LDownload,
  ExternalLink as LExternalLink,
  Eye as LEye,
  EyeOff as LEyeOff,
  File as LFile,
  FileIcon as LFileIcon,
  FileImage as LFileImage,
  FileSpreadsheet as LFileSpreadsheet,
  FileText as LFileText,
  Filter as LFilter,
  Fingerprint as LFingerprint,
  Flame as LFlame,
  Folder as LFolder,
  FolderKanban as LFolderKanban,
  FolderOpen as LFolderOpen,
  FolderPlus as LFolderPlus,
  Forward as LForward,
  Gauge as LGauge,
  GitBranch as LGitBranch,
  Github as LGithub,
  Globe as LGlobe,
  Globe2 as LGlobe2,
  Hash as LHash,
  Heading1 as LHeading1,
  Heading2 as LHeading2,
  History as LHistory,
  Home as LHome,
  Image as LImage,
  Inbox as LInbox,
  Info as LInfo,
  InfoIcon as LInfoIcon,
  Italic as LItalic,
  KanbanSquare as LKanbanSquare,
  Key as LKey,
  KeyRound as LKeyRound,
  Laptop as LLaptop,
  LayoutDashboard as LLayoutDashboard,
  LayoutGrid as LLayoutGrid,
  LayoutTemplate as LLayoutTemplate,
  LifeBuoy as LLifeBuoy,
  Lightbulb as LLightbulb,
  Link as LLink,
  Linkedin as LLinkedin,
  List as LList,
  ListChecks as LListChecks,
  ListFilter as LListFilter,
  ListOrdered as LListOrdered,
  Loader as LLoader,
  Loader2 as LLoader2,
  Loader2Icon as LLoader2Icon,
  Lock as LLock,
  LogIn as LLogIn,
  LogOut as LLogOut,
  Mail as LMail,
  MailCheck as LMailCheck,
  MapPin as LMapPin,
  Menu as LMenu,
  MessageSquare as LMessageSquare,
  Minus as LMinus,
  Monitor as LMonitor,
  Moon as LMoon,
  MoreHorizontal as LMoreHorizontal,
  MousePointer2 as LMousePointer2,
  OctagonXIcon as LOctagonXIcon,
  Palette as LPalette,
  PanelLeft as LPanelLeft,
  Paperclip as LPaperclip,
  Pencil as LPencil,
  Phone as LPhone,
  Plane as LPlane,
  PlayCircle as LPlayCircle,
  Plug as LPlug,
  Plus as LPlus,
  Quote as LQuote,
  Redo2 as LRedo2,
  RemoveFormatting as LRemoveFormatting,
  Rocket as LRocket,
  RotateCcw as LRotateCcw,
  RotateCw as LRotateCw,
  Search as LSearch,
  SearchX as LSearchX,
  Send as LSend,
  Settings as LSettings,
  Settings2 as LSettings2,
  ShieldAlert as LShieldAlert,
  ShieldCheck as LShieldCheck,
  Slack as LSlack,
  SlidersHorizontal as LSlidersHorizontal,
  Smartphone as LSmartphone,
  Sparkles as LSparkles,
  Star as LStar,
  Strikethrough as LStrikethrough,
  Sun as LSun,
  Table2 as LTable2,
  Tag as LTag,
  ThumbsUp as LThumbsUp,
  Timer as LTimer,
  Trash2 as LTrash2,
  TrendingDown as LTrendingDown,
  TrendingUp as LTrendingUp,
  TriangleAlert as LTriangleAlert,
  TriangleAlertIcon as LTriangleAlertIcon,
  Twitter as LTwitter,
  Underline as LUnderline,
  Undo2 as LUndo2,
  User as LUser,
  UserCircle as LUserCircle,
  UserPlus as LUserPlus,
  UserX as LUserX,
  Users as LUsers,
  Video as LVideo,
  Webhook as LWebhook,
  X as LX,
  XIcon as LXIcon,
  Zap as LZap,
} from 'lucide-vue-next'
import {
  ActivityIcon as HActivityIcon,
  Alert01Icon as HAlert01Icon,
  AlertCircleIcon as HAlertCircleIcon,
  AlignLeftIcon as HAlignLeftIcon,
  AlignRightIcon as HAlignRightIcon,
  ArchiveIcon as HArchiveIcon,
  ArrowDownIcon as HArrowDownIcon,
  ArrowDownRightIcon as HArrowDownRightIcon,
  ArrowLeftIcon as HArrowLeftIcon,
  ArrowRightIcon as HArrowRightIcon,
  ArrowUpDownIcon as HArrowUpDownIcon,
  ArrowUpIcon as HArrowUpIcon,
  ArrowUpRightIcon as HArrowUpRightIcon,
  AudioWaveformIcon as HAudioWaveformIcon,
  BadgeCheckIcon as HBadgeCheckIcon,
  BarChartIcon as HBarChartIcon,
  BellIcon as HBellIcon,
  BellOffIcon as HBellOffIcon,
  BoldIcon as HBoldIcon,
  BookOpenIcon as HBookOpenIcon,
  BoxesIcon as HBoxesIcon,
  BriefcaseIcon as HBriefcaseIcon,
  BugIcon as HBugIcon,
  Building02Icon as HBuilding02Icon,
  CalendarDaysIcon as HCalendarDaysIcon,
  CalendarIcon as HCalendarIcon,
  CalendarPlusIcon as HCalendarPlusIcon,
  CheckCheckIcon as HCheckCheckIcon,
  CheckIcon as HCheckIcon,
  CheckmarkCircle02Icon as HCheckmarkCircle02Icon,
  ChevronDownIcon as HChevronDownIcon,
  ChevronLeftIcon as HChevronLeftIcon,
  ChevronRightIcon as HChevronRightIcon,
  ChevronUpIcon as HChevronUpIcon,
  ChevronsLeftIcon as HChevronsLeftIcon,
  ChevronsRightIcon as HChevronsRightIcon,
  ChromeIcon as HChromeIcon,
  CircleCheckIcon as HCircleCheckIcon,
  CircleDotIcon as HCircleDotIcon,
  CircleIcon as HCircleIcon,
  ClockIcon as HClockIcon,
  CloudOffIcon as HCloudOffIcon,
  CodeIcon as HCodeIcon,
  CommandIcon as HCommandIcon,
  CopyIcon as HCopyIcon,
  CopyPlusIcon as HCopyPlusIcon,
  CreditCardIcon as HCreditCardIcon,
  Cursor02Icon as HCursor02Icon,
  Delete02Icon as HDelete02Icon,
  DollarSignIcon as HDollarSignIcon,
  DownloadIcon as HDownloadIcon,
  ExternalLinkIcon as HExternalLinkIcon,
  EyeIcon as HEyeIcon,
  EyeOffIcon as HEyeOffIcon,
  FileIcon as HFileIcon,
  FileImageIcon as HFileImageIcon,
  FileSpreadsheetIcon as HFileSpreadsheetIcon,
  FileTextIcon as HFileTextIcon,
  FilterIcon as HFilterIcon,
  FingerPrintIcon as HFingerPrintIcon,
  FlameIcon as HFlameIcon,
  FolderIcon as HFolderIcon,
  FolderKanbanIcon as HFolderKanbanIcon,
  FolderOpenIcon as HFolderOpenIcon,
  FolderPlusIcon as HFolderPlusIcon,
  ForwardIcon as HForwardIcon,
  GaugeIcon as HGaugeIcon,
  GitBranchIcon as HGitBranchIcon,
  GithubIcon as HGithubIcon,
  Globe02Icon as HGlobe02Icon,
  GlobeIcon as HGlobeIcon,
  HashIcon as HHashIcon,
  Heading01Icon as HHeading01Icon,
  Heading02Icon as HHeading02Icon,
  HistoryIcon as HHistoryIcon,
  HomeIcon as HHomeIcon,
  ImageIcon as HImageIcon,
  InboxIcon as HInboxIcon,
  InfoIcon as HInfoIcon,
  ItalicIcon as HItalicIcon,
  KeyIcon as HKeyIcon,
  KeyRoundIcon as HKeyRoundIcon,
  LaptopIcon as HLaptopIcon,
  Layout3ColumnIcon as HLayout3ColumnIcon,
  LayoutDashboardIcon as HLayoutDashboardIcon,
  LayoutGridIcon as HLayoutGridIcon,
  LayoutTemplateIcon as HLayoutTemplateIcon,
  LifebuoyIcon as HLifebuoyIcon,
  LightbulbIcon as HLightbulbIcon,
  LinkIcon as HLinkIcon,
  LinkedinIcon as HLinkedinIcon,
  ListChecksIcon as HListChecksIcon,
  ListFilterIcon as HListFilterIcon,
  ListIcon as HListIcon,
  ListOrderedIcon as HListOrderedIcon,
  LoaderIcon as HLoaderIcon,
  Loading03Icon as HLoading03Icon,
  LockIcon as HLockIcon,
  LogInIcon as HLogInIcon,
  LogOutIcon as HLogOutIcon,
  MailCheckIcon as HMailCheckIcon,
  MailIcon as HMailIcon,
  MapPinIcon as HMapPinIcon,
  MenuIcon as HMenuIcon,
  MessageSquareIcon as HMessageSquareIcon,
  MinusIcon as HMinusIcon,
  MonitorIcon as HMonitorIcon,
  MoonIcon as HMoonIcon,
  MoreHorizontalIcon as HMoreHorizontalIcon,
  OctagonXIcon as HOctagonXIcon,
  PaintBoardIcon as HPaintBoardIcon,
  PanelLeftIcon as HPanelLeftIcon,
  PaperclipIcon as HPaperclipIcon,
  PencilIcon as HPencilIcon,
  PhoneIcon as HPhoneIcon,
  PlaneIcon as HPlaneIcon,
  PlayCircleIcon as HPlayCircleIcon,
  PlugIcon as HPlugIcon,
  PlusIcon as HPlusIcon,
  QuoteIcon as HQuoteIcon,
  Redo02Icon as HRedo02Icon,
  RemoveFormattingIcon as HRemoveFormattingIcon,
  RocketIcon as HRocketIcon,
  RotateCcwIcon as HRotateCcwIcon,
  RotateCwIcon as HRotateCwIcon,
  SearchIcon as HSearchIcon,
  SearchXIcon as HSearchXIcon,
  SendIcon as HSendIcon,
  Settings02Icon as HSettings02Icon,
  SettingsIcon as HSettingsIcon,
  ShieldAlertIcon as HShieldAlertIcon,
  ShieldCheckIcon as HShieldCheckIcon,
  SlackIcon as HSlackIcon,
  SlidersHorizontalIcon as HSlidersHorizontalIcon,
  SmartphoneIcon as HSmartphoneIcon,
  SparklesIcon as HSparklesIcon,
  SquareKanbanIcon as HSquareKanbanIcon,
  StarIcon as HStarIcon,
  StrikethroughIcon as HStrikethroughIcon,
  SunIcon as HSunIcon,
  Table01Icon as HTable01Icon,
  TagIcon as HTagIcon,
  TextAlignCenterIcon as HTextAlignCenterIcon,
  ThumbsUpIcon as HThumbsUpIcon,
  TimerIcon as HTimerIcon,
  TrendingDownIcon as HTrendingDownIcon,
  TrendingUpIcon as HTrendingUpIcon,
  TriangleAlertIcon as HTriangleAlertIcon,
  TwitterIcon as HTwitterIcon,
  UnderlineIcon as HUnderlineIcon,
  Undo02Icon as HUndo02Icon,
  UserCircleIcon as HUserCircleIcon,
  UserIcon as HUserIcon,
  UserPlusIcon as HUserPlusIcon,
  UserXIcon as HUserXIcon,
  UsersIcon as HUsersIcon,
  VideoIcon as HVideoIcon,
  WebhookIcon as HWebhookIcon,
  XIcon as HXIcon,
  ZapIcon as HZapIcon,
} from '@hugeicons/core-free-icons'
import {
  IconActivity as TIconActivity,
  IconAdjustmentsHorizontal as TIconAdjustmentsHorizontal,
  IconAlertCircle as TIconAlertCircle,
  IconAlertOctagon as TIconAlertOctagon,
  IconAlertTriangle as TIconAlertTriangle,
  IconAlignCenter as TIconAlignCenter,
  IconAlignLeft as TIconAlignLeft,
  IconAlignRight as TIconAlignRight,
  IconArchive as TIconArchive,
  IconArrowBackUp as TIconArrowBackUp,
  IconArrowDown as TIconArrowDown,
  IconArrowDownRight as TIconArrowDownRight,
  IconArrowForwardUp as TIconArrowForwardUp,
  IconArrowLeft as TIconArrowLeft,
  IconArrowRight as TIconArrowRight,
  IconArrowUp as TIconArrowUp,
  IconArrowUpRight as TIconArrowUpRight,
  IconArrowsSort as TIconArrowsSort,
  IconBell as TIconBell,
  IconBellOff as TIconBellOff,
  IconBold as TIconBold,
  IconBolt as TIconBolt,
  IconBook as TIconBook,
  IconBrandChrome as TIconBrandChrome,
  IconBrandGithub as TIconBrandGithub,
  IconBrandLinkedin as TIconBrandLinkedin,
  IconBrandSlack as TIconBrandSlack,
  IconBrandX as TIconBrandX,
  IconBriefcase as TIconBriefcase,
  IconBug as TIconBug,
  IconBuilding as TIconBuilding,
  IconBulb as TIconBulb,
  IconCalendar as TIconCalendar,
  IconCalendarEvent as TIconCalendarEvent,
  IconCalendarPlus as TIconCalendarPlus,
  IconChartBar as TIconChartBar,
  IconCheck as TIconCheck,
  IconChecks as TIconChecks,
  IconChevronDown as TIconChevronDown,
  IconChevronLeft as TIconChevronLeft,
  IconChevronRight as TIconChevronRight,
  IconChevronUp as TIconChevronUp,
  IconChevronsLeft as TIconChevronsLeft,
  IconChevronsRight as TIconChevronsRight,
  IconCircle as TIconCircle,
  IconCircleCheck as TIconCircleCheck,
  IconCircleDot as TIconCircleDot,
  IconClearFormatting as TIconClearFormatting,
  IconClock as TIconClock,
  IconCloudOff as TIconCloudOff,
  IconCode as TIconCode,
  IconColumns3 as TIconColumns3,
  IconCommand as TIconCommand,
  IconCopy as TIconCopy,
  IconCopyPlus as TIconCopyPlus,
  IconCreditCard as TIconCreditCard,
  IconCurrencyDollar as TIconCurrencyDollar,
  IconDeviceDesktop as TIconDeviceDesktop,
  IconDeviceLaptop as TIconDeviceLaptop,
  IconDeviceMobile as TIconDeviceMobile,
  IconDots as TIconDots,
  IconDownload as TIconDownload,
  IconExternalLink as TIconExternalLink,
  IconEye as TIconEye,
  IconEyeOff as TIconEyeOff,
  IconFile as TIconFile,
  IconFileSpreadsheet as TIconFileSpreadsheet,
  IconFileText as TIconFileText,
  IconFilter as TIconFilter,
  IconFingerprint as TIconFingerprint,
  IconFlame as TIconFlame,
  IconFolder as TIconFolder,
  IconFolderOpen as TIconFolderOpen,
  IconFolderPlus as TIconFolderPlus,
  IconGauge as TIconGauge,
  IconGitBranch as TIconGitBranch,
  IconGlobe as TIconGlobe,
  IconH1 as TIconH1,
  IconH2 as TIconH2,
  IconHash as TIconHash,
  IconHistory as TIconHistory,
  IconHome as TIconHome,
  IconInbox as TIconInbox,
  IconInfoCircle as TIconInfoCircle,
  IconItalic as TIconItalic,
  IconKey as TIconKey,
  IconLayoutDashboard as TIconLayoutDashboard,
  IconLayoutGrid as TIconLayoutGrid,
  IconLayoutKanban as TIconLayoutKanban,
  IconLayoutSidebar as TIconLayoutSidebar,
  IconLifebuoy as TIconLifebuoy,
  IconLink as TIconLink,
  IconList as TIconList,
  IconListCheck as TIconListCheck,
  IconListNumbers as TIconListNumbers,
  IconLoader as TIconLoader,
  IconLoader2 as TIconLoader2,
  IconLock as TIconLock,
  IconLogin as TIconLogin,
  IconLogout as TIconLogout,
  IconMail as TIconMail,
  IconMailCheck as TIconMailCheck,
  IconMapPin as TIconMapPin,
  IconMenu as TIconMenu,
  IconMessage as TIconMessage,
  IconMinus as TIconMinus,
  IconMoon as TIconMoon,
  IconPackages as TIconPackages,
  IconPalette as TIconPalette,
  IconPaperclip as TIconPaperclip,
  IconPencil as TIconPencil,
  IconPhone as TIconPhone,
  IconPhoto as TIconPhoto,
  IconPlane as TIconPlane,
  IconPlayerPlay as TIconPlayerPlay,
  IconPlug as TIconPlug,
  IconPlus as TIconPlus,
  IconPointer as TIconPointer,
  IconQuote as TIconQuote,
  IconRocket as TIconRocket,
  IconRosetteDiscountCheck as TIconRosetteDiscountCheck,
  IconRotate as TIconRotate,
  IconRotateClockwise as TIconRotateClockwise,
  IconSearch as TIconSearch,
  IconSelector as TIconSelector,
  IconSend as TIconSend,
  IconSettings as TIconSettings,
  IconSettings2 as TIconSettings2,
  IconShieldCheck as TIconShieldCheck,
  IconShieldExclamation as TIconShieldExclamation,
  IconSparkles as TIconSparkles,
  IconStar as TIconStar,
  IconStopwatch as TIconStopwatch,
  IconStrikethrough as TIconStrikethrough,
  IconSun as TIconSun,
  IconTable as TIconTable,
  IconTag as TIconTag,
  IconTemplate as TIconTemplate,
  IconThumbUp as TIconThumbUp,
  IconTrash as TIconTrash,
  IconTrendingDown as TIconTrendingDown,
  IconTrendingUp as TIconTrendingUp,
  IconUnderline as TIconUnderline,
  IconUser as TIconUser,
  IconUserCircle as TIconUserCircle,
  IconUserPlus as TIconUserPlus,
  IconUserX as TIconUserX,
  IconUsers as TIconUsers,
  IconVideo as TIconVideo,
  IconWaveSine as TIconWaveSine,
  IconWebhook as TIconWebhook,
  IconWorld as TIconWorld,
  IconX as TIconX,
  IconZoomCancel as TIconZoomCancel,
} from '@tabler/icons-vue'
import {
  PhActivity,
  PhAirplane,
  PhAlignLeft,
  PhAlignRight,
  PhArchive,
  PhArrowBendUpRight,
  PhArrowClockwise,
  PhArrowCounterClockwise,
  PhArrowDown,
  PhArrowDownRight,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowUUpLeft,
  PhArrowUUpRight,
  PhArrowUp,
  PhArrowUpRight,
  PhArrowsDownUp,
  PhBell,
  PhBellSlash,
  PhBookOpen,
  PhBriefcase,
  PhBug,
  PhBuildings,
  PhCalendar,
  PhCalendarDots,
  PhCalendarPlus,
  PhCaretDoubleLeft,
  PhCaretDoubleRight,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhCaretUpDown,
  PhChartBar,
  PhChat,
  PhCheck,
  PhCheckCircle,
  PhChecks,
  PhCircle,
  PhCircleNotch,
  PhClock,
  PhClockCounterClockwise,
  PhCloudSlash,
  PhCode,
  PhColumns,
  PhCommand,
  PhCopy,
  PhCopySimple,
  PhCreditCard,
  PhCurrencyDollar,
  PhCursor,
  PhDeviceMobile,
  PhDotsThree,
  PhDownload,
  PhEnvelope,
  PhEnvelopeSimpleOpen,
  PhEraser,
  PhEye,
  PhEyeSlash,
  PhFile,
  PhFileImage,
  PhFileText,
  PhFileXls,
  PhFingerprint,
  PhFlame,
  PhFolder,
  PhFolderOpen,
  PhFolderPlus,
  PhFolderSimple,
  PhFunnel,
  PhFunnelSimple,
  PhGauge,
  PhGear,
  PhGearSix,
  PhGitBranch,
  PhGithubLogo,
  PhGlobe,
  PhGlobeSimple,
  PhGoogleChromeLogo,
  PhGridFour,
  PhHash,
  PhHouse,
  PhImage,
  PhInfo,
  PhKanban,
  PhKey,
  PhLaptop,
  PhLayout,
  PhLifebuoy,
  PhLightbulb,
  PhLightning,
  PhLink,
  PhLinkedinLogo,
  PhList,
  PhListChecks,
  PhListNumbers,
  PhLock,
  PhMagnifyingGlass,
  PhMagnifyingGlassMinus,
  PhMapPin,
  PhMinus,
  PhMonitor,
  PhMoon,
  PhPackage,
  PhPalette,
  PhPaperPlaneTilt,
  PhPaperclip,
  PhPencil,
  PhPhone,
  PhPlayCircle,
  PhPlug,
  PhPlus,
  PhProhibit,
  PhQuotes,
  PhRadioButton,
  PhRocket,
  PhSealCheck,
  PhShieldCheck,
  PhShieldWarning,
  PhSidebarSimple,
  PhSignIn,
  PhSignOut,
  PhSlackLogo,
  PhSlidersHorizontal,
  PhSparkle,
  PhSpinner,
  PhSquaresFour,
  PhStar,
  PhSun,
  PhTable,
  PhTag,
  PhTextAlignCenter,
  PhTextB,
  PhTextHOne,
  PhTextHTwo,
  PhTextItalic,
  PhTextStrikethrough,
  PhTextUnderline,
  PhThumbsUp,
  PhTimer,
  PhTrash,
  PhTray,
  PhTrendDown,
  PhTrendUp,
  PhUser,
  PhUserCircle,
  PhUserMinus,
  PhUserPlus,
  PhUsers,
  PhVideo,
  PhWarning,
  PhWarningCircle,
  PhWaveform,
  PhWebhooksLogo,
  PhX,
  PhXLogo,
} from '@phosphor-icons/vue'
import { useIconPack } from '@/composables/useIconPack'

type HugeIcon = typeof HActivityIcon

function packed(name: string, lucide: Component, icon: HugeIcon, tablerIcon: Component, phosphorIcon: Component): Component {
  return defineComponent({
    name: `Icon${name}`,
    inheritAttrs: false,
    setup(_, { attrs }) {
      const pack = useIconPack()
      // Size comes from the caller's size-* class in every pack.
      return () => {
        switch (pack.value) {
          case 'hugeicons': return h(HugeiconsIcon, { icon, size: 24, strokeWidth: 1.5, ...attrs })
          case 'tabler': return h(tablerIcon, { size: 24, stroke: 2, ...attrs })
          case 'phosphor': return h(phosphorIcon, { size: 24, weight: 'regular', ...attrs })
          default: return h(lucide, attrs)
        }
      }
    },
  })
}

export const Activity = packed('Activity', LActivity, HActivityIcon, TIconActivity, PhActivity)
export const AlertCircle = packed('AlertCircle', LAlertCircle, HAlertCircleIcon, TIconAlertCircle, PhWarningCircle)
export const AlertTriangle = packed('AlertTriangle', LAlertTriangle, HAlert01Icon, TIconAlertTriangle, PhWarning)
export const AlignCenter = packed('AlignCenter', LAlignCenter, HTextAlignCenterIcon, TIconAlignCenter, PhTextAlignCenter)
export const AlignLeft = packed('AlignLeft', LAlignLeft, HAlignLeftIcon, TIconAlignLeft, PhAlignLeft)
export const AlignRight = packed('AlignRight', LAlignRight, HAlignRightIcon, TIconAlignRight, PhAlignRight)
export const Archive = packed('Archive', LArchive, HArchiveIcon, TIconArchive, PhArchive)
export const ArrowDown = packed('ArrowDown', LArrowDown, HArrowDownIcon, TIconArrowDown, PhArrowDown)
export const ArrowDownRight = packed('ArrowDownRight', LArrowDownRight, HArrowDownRightIcon, TIconArrowDownRight, PhArrowDownRight)
export const ArrowLeft = packed('ArrowLeft', LArrowLeft, HArrowLeftIcon, TIconArrowLeft, PhArrowLeft)
export const ArrowRight = packed('ArrowRight', LArrowRight, HArrowRightIcon, TIconArrowRight, PhArrowRight)
export const ArrowUp = packed('ArrowUp', LArrowUp, HArrowUpIcon, TIconArrowUp, PhArrowUp)
export const ArrowUpDown = packed('ArrowUpDown', LArrowUpDown, HArrowUpDownIcon, TIconArrowsSort, PhArrowsDownUp)
export const ArrowUpRight = packed('ArrowUpRight', LArrowUpRight, HArrowUpRightIcon, TIconArrowUpRight, PhArrowUpRight)
export const AudioWaveform = packed('AudioWaveform', LAudioWaveform, HAudioWaveformIcon, TIconWaveSine, PhWaveform)
export const BadgeCheck = packed('BadgeCheck', LBadgeCheck, HBadgeCheckIcon, TIconRosetteDiscountCheck, PhSealCheck)
export const BarChart3 = packed('BarChart3', LBarChart3, HBarChartIcon, TIconChartBar, PhChartBar)
export const Bell = packed('Bell', LBell, HBellIcon, TIconBell, PhBell)
export const BellOff = packed('BellOff', LBellOff, HBellOffIcon, TIconBellOff, PhBellSlash)
export const Bold = packed('Bold', LBold, HBoldIcon, TIconBold, PhTextB)
export const BookOpen = packed('BookOpen', LBookOpen, HBookOpenIcon, TIconBook, PhBookOpen)
export const Boxes = packed('Boxes', LBoxes, HBoxesIcon, TIconPackages, PhPackage)
export const Briefcase = packed('Briefcase', LBriefcase, HBriefcaseIcon, TIconBriefcase, PhBriefcase)
export const Bug = packed('Bug', LBug, HBugIcon, TIconBug, PhBug)
export const Building2 = packed('Building2', LBuilding2, HBuilding02Icon, TIconBuilding, PhBuildings)
export const Calendar = packed('Calendar', LCalendar, HCalendarIcon, TIconCalendar, PhCalendar)
export const CalendarDays = packed('CalendarDays', LCalendarDays, HCalendarDaysIcon, TIconCalendarEvent, PhCalendarDots)
export const CalendarIcon = packed('CalendarIcon', LCalendarIcon, HCalendarIcon, TIconCalendar, PhCalendar)
export const CalendarPlus = packed('CalendarPlus', LCalendarPlus, HCalendarPlusIcon, TIconCalendarPlus, PhCalendarPlus)
export const Check = packed('Check', LCheck, HCheckIcon, TIconCheck, PhCheck)
export const CheckCheck = packed('CheckCheck', LCheckCheck, HCheckCheckIcon, TIconChecks, PhChecks)
export const CheckCircle2 = packed('CheckCircle2', LCheckCircle2, HCheckmarkCircle02Icon, TIconCircleCheck, PhCheckCircle)
export const ChevronDown = packed('ChevronDown', LChevronDown, HChevronDownIcon, TIconChevronDown, PhCaretDown)
export const ChevronDownIcon = packed('ChevronDownIcon', LChevronDownIcon, HChevronDownIcon, TIconChevronDown, PhCaretDown)
export const ChevronLeft = packed('ChevronLeft', LChevronLeft, HChevronLeftIcon, TIconChevronLeft, PhCaretLeft)
export const ChevronRight = packed('ChevronRight', LChevronRight, HChevronRightIcon, TIconChevronRight, PhCaretRight)
export const ChevronUp = packed('ChevronUp', LChevronUp, HChevronUpIcon, TIconChevronUp, PhCaretUp)
export const ChevronsLeft = packed('ChevronsLeft', LChevronsLeft, HChevronsLeftIcon, TIconChevronsLeft, PhCaretDoubleLeft)
export const ChevronsRight = packed('ChevronsRight', LChevronsRight, HChevronsRightIcon, TIconChevronsRight, PhCaretDoubleRight)
export const ChevronsUpDown = packed('ChevronsUpDown', LChevronsUpDown, HArrowUpDownIcon, TIconSelector, PhCaretUpDown)
export const Chrome = packed('Chrome', LChrome, HChromeIcon, TIconBrandChrome, PhGoogleChromeLogo)
export const Circle = packed('Circle', LCircle, HCircleIcon, TIconCircle, PhCircle)
export const CircleAlert = packed('CircleAlert', LCircleAlert, HAlertCircleIcon, TIconAlertCircle, PhWarningCircle)
export const CircleCheckIcon = packed('CircleCheckIcon', LCircleCheckIcon, HCircleCheckIcon, TIconCircleCheck, PhCheckCircle)
export const CircleDot = packed('CircleDot', LCircleDot, HCircleDotIcon, TIconCircleDot, PhRadioButton)
export const Clock = packed('Clock', LClock, HClockIcon, TIconClock, PhClock)
export const CloudOff = packed('CloudOff', LCloudOff, HCloudOffIcon, TIconCloudOff, PhCloudSlash)
export const Code = packed('Code', LCode, HCodeIcon, TIconCode, PhCode)
export const Columns3 = packed('Columns3', LColumns3, HLayout3ColumnIcon, TIconColumns3, PhColumns)
export const Command = packed('Command', LCommand, HCommandIcon, TIconCommand, PhCommand)
export const Copy = packed('Copy', LCopy, HCopyIcon, TIconCopy, PhCopy)
export const CopyPlus = packed('CopyPlus', LCopyPlus, HCopyPlusIcon, TIconCopyPlus, PhCopySimple)
export const CreditCard = packed('CreditCard', LCreditCard, HCreditCardIcon, TIconCreditCard, PhCreditCard)
export const DollarSign = packed('DollarSign', LDollarSign, HDollarSignIcon, TIconCurrencyDollar, PhCurrencyDollar)
export const Download = packed('Download', LDownload, HDownloadIcon, TIconDownload, PhDownload)
export const ExternalLink = packed('ExternalLink', LExternalLink, HExternalLinkIcon, TIconExternalLink, PhArrowSquareOut)
export const Eye = packed('Eye', LEye, HEyeIcon, TIconEye, PhEye)
export const EyeOff = packed('EyeOff', LEyeOff, HEyeOffIcon, TIconEyeOff, PhEyeSlash)
export const File = packed('File', LFile, HFileIcon, TIconFile, PhFile)
export const FileIcon = packed('FileIcon', LFileIcon, HFileIcon, TIconFile, PhFile)
export const FileImage = packed('FileImage', LFileImage, HFileImageIcon, TIconPhoto, PhFileImage)
export const FileSpreadsheet = packed('FileSpreadsheet', LFileSpreadsheet, HFileSpreadsheetIcon, TIconFileSpreadsheet, PhFileXls)
export const FileText = packed('FileText', LFileText, HFileTextIcon, TIconFileText, PhFileText)
export const Filter = packed('Filter', LFilter, HFilterIcon, TIconFilter, PhFunnel)
export const Fingerprint = packed('Fingerprint', LFingerprint, HFingerPrintIcon, TIconFingerprint, PhFingerprint)
export const Flame = packed('Flame', LFlame, HFlameIcon, TIconFlame, PhFlame)
export const Folder = packed('Folder', LFolder, HFolderIcon, TIconFolder, PhFolder)
export const FolderKanban = packed('FolderKanban', LFolderKanban, HFolderKanbanIcon, TIconFolder, PhFolderSimple)
export const FolderOpen = packed('FolderOpen', LFolderOpen, HFolderOpenIcon, TIconFolderOpen, PhFolderOpen)
export const FolderPlus = packed('FolderPlus', LFolderPlus, HFolderPlusIcon, TIconFolderPlus, PhFolderPlus)
export const Forward = packed('Forward', LForward, HForwardIcon, TIconArrowForwardUp, PhArrowBendUpRight)
export const Gauge = packed('Gauge', LGauge, HGaugeIcon, TIconGauge, PhGauge)
export const GitBranch = packed('GitBranch', LGitBranch, HGitBranchIcon, TIconGitBranch, PhGitBranch)
export const Github = packed('Github', LGithub, HGithubIcon, TIconBrandGithub, PhGithubLogo)
export const Globe = packed('Globe', LGlobe, HGlobeIcon, TIconGlobe, PhGlobe)
export const Globe2 = packed('Globe2', LGlobe2, HGlobe02Icon, TIconWorld, PhGlobeSimple)
export const Hash = packed('Hash', LHash, HHashIcon, TIconHash, PhHash)
export const Heading1 = packed('Heading1', LHeading1, HHeading01Icon, TIconH1, PhTextHOne)
export const Heading2 = packed('Heading2', LHeading2, HHeading02Icon, TIconH2, PhTextHTwo)
export const History = packed('History', LHistory, HHistoryIcon, TIconHistory, PhClockCounterClockwise)
export const Home = packed('Home', LHome, HHomeIcon, TIconHome, PhHouse)
export const Image = packed('Image', LImage, HImageIcon, TIconPhoto, PhImage)
export const Inbox = packed('Inbox', LInbox, HInboxIcon, TIconInbox, PhTray)
export const Info = packed('Info', LInfo, HInfoIcon, TIconInfoCircle, PhInfo)
export const InfoIcon = packed('InfoIcon', LInfoIcon, HInfoIcon, TIconInfoCircle, PhInfo)
export const Italic = packed('Italic', LItalic, HItalicIcon, TIconItalic, PhTextItalic)
export const KanbanSquare = packed('KanbanSquare', LKanbanSquare, HSquareKanbanIcon, TIconLayoutKanban, PhKanban)
export const Key = packed('Key', LKey, HKeyIcon, TIconKey, PhKey)
export const KeyRound = packed('KeyRound', LKeyRound, HKeyRoundIcon, TIconKey, PhKey)
export const Laptop = packed('Laptop', LLaptop, HLaptopIcon, TIconDeviceLaptop, PhLaptop)
export const LayoutDashboard = packed('LayoutDashboard', LLayoutDashboard, HLayoutDashboardIcon, TIconLayoutDashboard, PhSquaresFour)
export const LayoutGrid = packed('LayoutGrid', LLayoutGrid, HLayoutGridIcon, TIconLayoutGrid, PhGridFour)
export const LayoutTemplate = packed('LayoutTemplate', LLayoutTemplate, HLayoutTemplateIcon, TIconTemplate, PhLayout)
export const LifeBuoy = packed('LifeBuoy', LLifeBuoy, HLifebuoyIcon, TIconLifebuoy, PhLifebuoy)
export const Lightbulb = packed('Lightbulb', LLightbulb, HLightbulbIcon, TIconBulb, PhLightbulb)
export const Link = packed('Link', LLink, HLinkIcon, TIconLink, PhLink)
export const Linkedin = packed('Linkedin', LLinkedin, HLinkedinIcon, TIconBrandLinkedin, PhLinkedinLogo)
export const List = packed('List', LList, HListIcon, TIconList, PhList)
export const ListChecks = packed('ListChecks', LListChecks, HListChecksIcon, TIconListCheck, PhListChecks)
export const ListFilter = packed('ListFilter', LListFilter, HListFilterIcon, TIconFilter, PhFunnelSimple)
export const ListOrdered = packed('ListOrdered', LListOrdered, HListOrderedIcon, TIconListNumbers, PhListNumbers)
export const Loader = packed('Loader', LLoader, HLoaderIcon, TIconLoader, PhSpinner)
export const Loader2 = packed('Loader2', LLoader2, HLoading03Icon, TIconLoader2, PhCircleNotch)
export const Loader2Icon = packed('Loader2Icon', LLoader2Icon, HLoading03Icon, TIconLoader2, PhCircleNotch)
export const Lock = packed('Lock', LLock, HLockIcon, TIconLock, PhLock)
export const LogIn = packed('LogIn', LLogIn, HLogInIcon, TIconLogin, PhSignIn)
export const LogOut = packed('LogOut', LLogOut, HLogOutIcon, TIconLogout, PhSignOut)
export const Mail = packed('Mail', LMail, HMailIcon, TIconMail, PhEnvelope)
export const MailCheck = packed('MailCheck', LMailCheck, HMailCheckIcon, TIconMailCheck, PhEnvelopeSimpleOpen)
export const MapPin = packed('MapPin', LMapPin, HMapPinIcon, TIconMapPin, PhMapPin)
export const Menu = packed('Menu', LMenu, HMenuIcon, TIconMenu, PhList)
export const MessageSquare = packed('MessageSquare', LMessageSquare, HMessageSquareIcon, TIconMessage, PhChat)
export const Minus = packed('Minus', LMinus, HMinusIcon, TIconMinus, PhMinus)
export const Monitor = packed('Monitor', LMonitor, HMonitorIcon, TIconDeviceDesktop, PhMonitor)
export const Moon = packed('Moon', LMoon, HMoonIcon, TIconMoon, PhMoon)
export const MoreHorizontal = packed('MoreHorizontal', LMoreHorizontal, HMoreHorizontalIcon, TIconDots, PhDotsThree)
export const MousePointer2 = packed('MousePointer2', LMousePointer2, HCursor02Icon, TIconPointer, PhCursor)
export const OctagonXIcon = packed('OctagonXIcon', LOctagonXIcon, HOctagonXIcon, TIconAlertOctagon, PhProhibit)
export const Palette = packed('Palette', LPalette, HPaintBoardIcon, TIconPalette, PhPalette)
export const PanelLeft = packed('PanelLeft', LPanelLeft, HPanelLeftIcon, TIconLayoutSidebar, PhSidebarSimple)
export const Paperclip = packed('Paperclip', LPaperclip, HPaperclipIcon, TIconPaperclip, PhPaperclip)
export const Pencil = packed('Pencil', LPencil, HPencilIcon, TIconPencil, PhPencil)
export const Phone = packed('Phone', LPhone, HPhoneIcon, TIconPhone, PhPhone)
export const Plane = packed('Plane', LPlane, HPlaneIcon, TIconPlane, PhAirplane)
export const PlayCircle = packed('PlayCircle', LPlayCircle, HPlayCircleIcon, TIconPlayerPlay, PhPlayCircle)
export const Plug = packed('Plug', LPlug, HPlugIcon, TIconPlug, PhPlug)
export const Plus = packed('Plus', LPlus, HPlusIcon, TIconPlus, PhPlus)
export const Quote = packed('Quote', LQuote, HQuoteIcon, TIconQuote, PhQuotes)
export const Redo2 = packed('Redo2', LRedo2, HRedo02Icon, TIconArrowForwardUp, PhArrowUUpRight)
export const RemoveFormatting = packed('RemoveFormatting', LRemoveFormatting, HRemoveFormattingIcon, TIconClearFormatting, PhEraser)
export const Rocket = packed('Rocket', LRocket, HRocketIcon, TIconRocket, PhRocket)
export const RotateCcw = packed('RotateCcw', LRotateCcw, HRotateCcwIcon, TIconRotate, PhArrowCounterClockwise)
export const RotateCw = packed('RotateCw', LRotateCw, HRotateCwIcon, TIconRotateClockwise, PhArrowClockwise)
export const Search = packed('Search', LSearch, HSearchIcon, TIconSearch, PhMagnifyingGlass)
export const SearchX = packed('SearchX', LSearchX, HSearchXIcon, TIconZoomCancel, PhMagnifyingGlassMinus)
export const Send = packed('Send', LSend, HSendIcon, TIconSend, PhPaperPlaneTilt)
export const Settings = packed('Settings', LSettings, HSettingsIcon, TIconSettings, PhGear)
export const Settings2 = packed('Settings2', LSettings2, HSettings02Icon, TIconSettings2, PhGearSix)
export const ShieldAlert = packed('ShieldAlert', LShieldAlert, HShieldAlertIcon, TIconShieldExclamation, PhShieldWarning)
export const ShieldCheck = packed('ShieldCheck', LShieldCheck, HShieldCheckIcon, TIconShieldCheck, PhShieldCheck)
export const Slack = packed('Slack', LSlack, HSlackIcon, TIconBrandSlack, PhSlackLogo)
export const SlidersHorizontal = packed('SlidersHorizontal', LSlidersHorizontal, HSlidersHorizontalIcon, TIconAdjustmentsHorizontal, PhSlidersHorizontal)
export const Smartphone = packed('Smartphone', LSmartphone, HSmartphoneIcon, TIconDeviceMobile, PhDeviceMobile)
export const Sparkles = packed('Sparkles', LSparkles, HSparklesIcon, TIconSparkles, PhSparkle)
export const Star = packed('Star', LStar, HStarIcon, TIconStar, PhStar)
export const Strikethrough = packed('Strikethrough', LStrikethrough, HStrikethroughIcon, TIconStrikethrough, PhTextStrikethrough)
export const Sun = packed('Sun', LSun, HSunIcon, TIconSun, PhSun)
export const Table2 = packed('Table2', LTable2, HTable01Icon, TIconTable, PhTable)
export const Tag = packed('Tag', LTag, HTagIcon, TIconTag, PhTag)
export const ThumbsUp = packed('ThumbsUp', LThumbsUp, HThumbsUpIcon, TIconThumbUp, PhThumbsUp)
export const Timer = packed('Timer', LTimer, HTimerIcon, TIconStopwatch, PhTimer)
export const Trash2 = packed('Trash2', LTrash2, HDelete02Icon, TIconTrash, PhTrash)
export const TrendingDown = packed('TrendingDown', LTrendingDown, HTrendingDownIcon, TIconTrendingDown, PhTrendDown)
export const TrendingUp = packed('TrendingUp', LTrendingUp, HTrendingUpIcon, TIconTrendingUp, PhTrendUp)
export const TriangleAlert = packed('TriangleAlert', LTriangleAlert, HTriangleAlertIcon, TIconAlertTriangle, PhWarning)
export const TriangleAlertIcon = packed('TriangleAlertIcon', LTriangleAlertIcon, HTriangleAlertIcon, TIconAlertTriangle, PhWarning)
export const Twitter = packed('Twitter', LTwitter, HTwitterIcon, TIconBrandX, PhXLogo)
export const Underline = packed('Underline', LUnderline, HUnderlineIcon, TIconUnderline, PhTextUnderline)
export const Undo2 = packed('Undo2', LUndo2, HUndo02Icon, TIconArrowBackUp, PhArrowUUpLeft)
export const User = packed('User', LUser, HUserIcon, TIconUser, PhUser)
export const UserCircle = packed('UserCircle', LUserCircle, HUserCircleIcon, TIconUserCircle, PhUserCircle)
export const UserPlus = packed('UserPlus', LUserPlus, HUserPlusIcon, TIconUserPlus, PhUserPlus)
export const UserX = packed('UserX', LUserX, HUserXIcon, TIconUserX, PhUserMinus)
export const Users = packed('Users', LUsers, HUsersIcon, TIconUsers, PhUsers)
export const Video = packed('Video', LVideo, HVideoIcon, TIconVideo, PhVideo)
export const Webhook = packed('Webhook', LWebhook, HWebhookIcon, TIconWebhook, PhWebhooksLogo)
export const X = packed('X', LX, HXIcon, TIconX, PhX)
export const XIcon = packed('XIcon', LXIcon, HXIcon, TIconX, PhX)
export const Zap = packed('Zap', LZap, HZapIcon, TIconBolt, PhLightning)
